name: Continuous Deployment via SSH

on:
  push:
    branches:
      - master 
  pull_request:
    branches:
      - master 

jobs:
  # The 'ci' job should run first (or this can be a single job if you skip CI tests)
  deploy:
    runs-on: ubuntu-latest
    
    # Optional: ensure this job only runs if a previous 'test' job succeeded
    # needs: [test] 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          # SSH Credentials are pulled securely from GitHub Secrets
          host    : 13.204.116.118                  # <-- You need to create this secret 
          username: 'abdullah'                      # <-- You need to create this secret
          key     : ${{ secrets.HOME_SSH }}         # <-- This is the private key you set up
          
          # ----------------------------------------------------------------
          # COMMANDS TO RUN ON YOUR SERVER (Deployment Logic)
          # ----------------------------------------------------------------
          script: |
            echo "Deployment started for ${{ github.sha }}"
            
            # 1. Navigate to your project directory (the root of your domain)
            cd /home/abdullah/web/dev.reworqx.com/public_html
            
            # 2. Pull the latest code from GitHub
            git pull origin master
            
            # 3. Install/Update PHP Dependencies (excluding development packages)
            # /usr/bin/composer install --no-dev --prefer-dist --optimize-autoloader
            
            # 4. Clear any caches (if using a framework like Laravel or Symfony)
            # if [ -f artisan ]; then
            #   php artisan migrate --force 
            #   php artisan cache:clear
            # fi

            # php artisan optimize:clear
            
            echo "Deployment finished successfully!"