name: Continuous Deployment via SSH

on:
  push:
    branches:
      - master 
  pull_request:
    branches:
      - master 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host    : 127.0.0.1                 
          username: 'rayhan'                      
          key     : ${{ secrets.HOME_SSH }}         
          
          script: |
            echo "Deployment started for ${{ github.sha }}"

            cd /home/abdullah/web/dev.local.com/public_html

            git pull origin master

            # composer install --no-dev --prefer-dist --optimize-autoloader
            
            # if [ -f artisan ]; then
            #   php artisan migrate --force 
            #   php artisan cache:clear
            # fi

            # php artisan optimize:clear
            
            echo "Deployment finished successfully!"